import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Activity, ArrowUpRight, Check, ChevronRight, Copy, Database, FileText, Terminal, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { ExecutionEvent, ExecutionModel, ExecutionTask } from '@/types/execution';
export type InspectorTab = 'synthesis' | 'node' | 'rag';
interface Props { events: ExecutionEvent[]; run?: ExecutionModel; selected?: ExecutionTask; tab: InspectorTab; setTab: (tab: InspectorTab) => void; running: boolean }
export function TaskDetails({ task }: { task: ExecutionTask }) {
  return <div className="task-details"><div className="detail-title"><strong>{task.title}</strong><span className={`state-text status-${task.status.toLowerCase()}`}>{task.status}</span></div><dl><dt>Task ID</dt><dd>{task.id}</dd><dt>Capability</dt><dd>{task.capability || task.type}</dd><dt>Dependencies</dt><dd>{task.dependencies.length ? task.dependencies.join(', ') : 'Not provided'}</dd>{task.durationMs !== undefined && <><dt>Duration</dt><dd>{task.durationMs} ms</dd></>}{task.agent && <><dt>Agent</dt><dd>{task.agent}</dd></>}</dl>{task.description && <p>{task.description}</p>}{task.input && <section><h4>INPUT</h4><p>{task.input}</p></section>}{task.output && <section><h4>OUTPUT</h4><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{task.output}</ReactMarkdown></div></section>}{task.metadata && Object.keys(task.metadata).length > 0 && <section><h4>METADATA</h4><pre>{JSON.stringify(task.metadata, null, 2)}</pre></section>}</div>;
}
export function FloatingInspector({ task, onClose }: { task: ExecutionTask; onClose: () => void }) { return <aside className="floating-inspector"><header><span><ChevronRight size={13}/> NODE INSPECTOR</span><Button size="icon" variant="ghost" aria-label="Close node inspector" onClick={onClose}><X/></Button></header><div><TaskDetails task={task}/></div></aside>; }
export function ExecutionConsole({ events, run, selected, tab, setTab, running }: Props) {
  const [copied, setCopied] = useState(false);
  return <section className="execution-console">
    <div className="event-panel"><header className="console-header"><div><Terminal size={13}/><span>Live Event Stream</span><span className="subtle-tag">& TELEMETRY</span></div><span className="event-count">{events.length} EVENTS</span></header><div className="event-body">{events.length ? events.map(event => <div className="event-line" key={event.id}><span className="event-time">{event.time || 'TRACE'}</span><span className={`event-label ${event.status === 'FAILED' ? 'text-destructive' : event.status === 'COMPLETED' ? 'text-success' : 'text-primary'}`}><ChevronRight size={10}/>{event.label}</span><span className="event-message">{event.message}</span><span className="event-source">{event.durationMs !== undefined ? `${event.durationMs}ms · ` : ''}{event.source}</span></div>) : <div className="event-idle"><span className="terminal-prompt">❯</span><span>Awaiting task submission<span className="cursor-blink">_</span></span><span className="event-source">IDLE</span></div>}</div><footer><span><Activity size={11}/>{running ? 'REQUEST IN FLIGHT' : run ? 'POST-RUN TRACE' : 'NO ACTIVE EXECUTION'}</span><span>{run ? `${run.tasks.length} TASKS` : 'LATENCY —'}</span><span>{run ? `${run.events.length} TRACE ENTRIES` : 'TOKENS —'}</span></footer></div>
    <div className="inspector-panel"><header className="console-header"><div className="inspector-tabs" role="tablist">{([{ id: 'synthesis', label: 'Final Synthesis', icon: FileText }, { id: 'node', label: 'Node Inspector', icon: ArrowUpRight }, { id: 'rag', label: 'RAG Provenance', icon: Database }] as const).map(item => <Button role="tab" aria-selected={tab === item.id} key={item.id} variant="ghost" size="sm" className={tab === item.id ? 'tab-active' : ''} onClick={() => setTab(item.id)}><item.icon size={12}/>{item.label}</Button>)}</div>{tab === 'synthesis' && <Button size="icon" variant="ghost" aria-label="Copy final answer" title="Copy final answer" disabled={!run?.finalAnswer} onClick={async () => { if (run?.finalAnswer) { try { await navigator.clipboard.writeText(run.finalAnswer); setCopied(true); } catch { setCopied(false); } } }}>{copied ? <Check/> : <Copy/>}</Button>}</header><div className="inspector-body">
    {tab === 'synthesis' && (run?.finalAnswer ? <><div className="answer-meta">RUN / {run.runId}</div><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{run.finalAnswer}</ReactMarkdown></div></> : <div className="inspector-empty"><span className="empty-icon"><FileText size={21}/></span><div><strong>{running ? 'Waiting for synthesis' : 'Your final synthesis will appear here'}</strong><p>{running ? 'The API returns results when execution completes.' : 'No final answer returned yet'}</p></div></div>)}
    {tab === 'node' && (selected ? <TaskDetails task={selected}/> : <div className="inspector-empty"><span className="empty-icon"><ArrowUpRight size={21}/></span><div><strong>No node selected</strong><p>Awaiting node selection</p></div></div>)}
    {tab === 'rag' && (run?.chunks.length ? <div className="provenance">{run.chunks.map((c, i) => <article key={i}><strong>{c.source || c.documentId || `Retrieved chunk ${i + 1}`}</strong><span>{c.chunkIndex !== undefined ? `Chunk #${c.chunkIndex}` : ''}{c.similarity !== undefined ? ` · Similarity ${c.similarity.toFixed(3)}` : ''}</span><p>{c.content || 'Chunk content not exposed'}</p></article>)}</div> : <div className="inspector-empty"><span className="empty-icon"><Database size={21}/></span><div><strong>Retrieval telemetry unavailable</strong><p>Retrieval provenance is not exposed for this run.</p></div></div>)}
    </div></div>
  </section>;
}
